#!/usr/bin/env python3
# -*- coding: utf-8 -*-
'''
This file belong to [TimeBags Project](https://timebags.org)
'''

import sys
import gui
import cli


def main():
    ''' Main '''

    if len(sys.argv) == 1:
        ret = gui.main()
    elif len(sys.argv) > 1:
        ret = cli.main(sys.argv[1])
    if ret:
        return 0
    return 1


if __name__ == '__main__':
    sys.exit(main())
