#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2019 The TimeBags developers
#
# This file is part of the TimeBags software.
#
# It is subject to the license terms in the LICENSE file
# found in the top-level directory of this distribution.
#
# No part of the Timebags software, including this file, may be copied,
# modified, propagated, or distributed except according to the terms
# contained in the LICENSE file.

'''
This file belong to [TimeBags Project](https://timebags.org)
'''

import sys
import logging

import gui
import cli


def main():
    ''' Main '''

    logging.basicConfig(level=logging.DEBUG)

    # TBD: it's better to have timebags-qt and timebags-cli and check sys.argv[0],
    #      but how to do with pyinstaller and AppImage?
    if len(sys.argv) == 1:
        # TBD: check an option like --gui
        ret = gui.main()
    elif len(sys.argv) > 1:
        ret = cli.main(sys.argv[1:])
    if ret is not None:
        return 0
    return 1


if __name__ == '__main__':
    sys.exit(main())
