#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2019 The TimeBags developers
#
# This file is part of the TimeBags software.
#
# It is subject to the license terms in the LICENSE file
# found in the top-level directory of this distribution.
#
# No part of the TimeBags software, including this file, may be copied,
# modified, propagated, or distributed except according to the terms
# contained in the LICENSE file.

'''
This file belong to [TimeBags Project](https://timebags.org)
'''

import sys
import logging
from pprint import pprint

import settings
import gui
import core


def main():
    ''' Main '''

    # initialize env and global vars
    settings.init()

    # default log to a file at DEBUG level if running in GUI mode
    #logfile = os.path.join(settings.path_conf_dir, "debug.log")
    #logging.basicConfig(filename=logfile, filemode='w', level=logging.DEBUG)
    logging.basicConfig(level=logging.DEBUG)

    # TBD: it's better to have --cli and check sys.argv[0] also for gui params
    #      but now just check if there are params
    if len(sys.argv) == 1:
        gui.main()
    elif len(sys.argv) > 1:
        ret = core.main(sys.argv[1:])
        pprint(ret)
        if ret is not None:
            sys.exit(0)
        print("ERROR: check log for details")
        sys.exit(1)


if __name__ == '__main__':
    main()
