#!/bin/sh

SELF=$(readlink -f "$0")
HERE=${SELF%/*}
export TIMEBAGS="${HERE}/runtime/TimeBags"
export PATH="${HERE}/runtime:${HERE}/${PATH:+:$PATH}"
EXEC=$(grep -e '^Exec=.*' "${HERE}"/*.desktop | head -n 1 | cut -d "=" -f 2 | cut -d " " -f 1)
exec "${EXEC}" "$@"
